### ISSUE TITLE
We are getting lots of "Error R14 (Memory quota exceeded)" on Herkou

### ISSUE THREAD

**Issue by pepjo** [helpyio/helpy#39]
Hi again,

sometimes we get a 500 error when we try to post a new article, I've check the logs and I found
that `Error R14 (Memory quota exceeded)` keeps repeating all over again.

I've also found that this error keeps repeating:
````
Rendered admin/articles.html.erb within layouts/admin (13.3ms)
ActionView::Template::Error (undefined method `gsub' for nil:NilClass):
22: <span id="row-<%= doc.id %>" data-toggle="dropdown" aria-expanded="false" class='btn dropdown-toggle glyphicon glyphicon-align-justify'></span>
23: <ul class="dropdown-menu dropdown-menu-right" role="menu">
24: <li><%= link_to t(:edit, default: 'Edit'), edit_category_doc_path(doc.category.id, doc.id, lang: I18n.locale) %></li>
25: <li><%= link_to t(:delete, default: 'Delete'), doc, data: {confirm: t(:delete_confirm, default: 'Please confirm you really want to DELETE this')}, method: :delete, remote: true, class: 'less-important' %></li>
26: <li><%= link_to t(:view_on_site, default: 'View on Site'), category_doc_path(doc.category, doc), {target: "_blank"} %></li>
27: </ul>
28: </div>
app/models/doc.rb:56:in `to_param'
app/views/admin/articles.html.erb:25:in `block in _app_views_admin_articles_html_erb___2712434889001218502_70267151824380'
app/views/admin/articles.html.erb:12:in `_app_views_admin_articles_html_erb___2712434889001218502_70267151824380'
app/controllers/admin_controller.rb:29:in `articles'

Started GET "/admin/content/5/articles" for 80.64.37.217 at 2016-02-20 10:10:57 +0000
Parameters: {"category_id"=>"5"}
!!! initiate tracker without client id !!!
Processing by AdminController#articles as HTML
User Load (0.8ms) SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT 1 [["id", 1]]
Category Load (0.5ms) SELECT "categories".* FROM "categories" WHERE "categories"."id" = $1 ORDER BY "categories"."id" ASC LIMIT 1 [["id", 5]]
Doc Load (0.6ms) SELECT "docs".* FROM "docs" WHERE "docs"."category_id" = $1 ORDER BY rank ASC, title ASC [["category_id", 5]]
(1.4ms) SELECT COUNT(*) FROM "doc_translations" WHERE "doc_translations"."doc_id" = $1 AND "doc_translations"."locale" = $2 [["doc_id", 7], ["locale", "en"]]
(0.5ms) SELECT COUNT(*) FROM "doc_translations" WHERE "doc_translations"."doc_id" = $1 AND "doc_translations"."locale" = $2 [["doc_id", 7], ["locale", "es"]]
Completed 500 Internal Server Error in 45ms (ActiveRecord: 6.5ms)
````

I've tried to track down the issue but I've never worked with Ruby nor Ruby on Rails.

So you have any Idea about what may cause the issue?

**Comment by scott** [comment]
I am not too sure about the memory quota thing.  Are you using a free Heroku account or have you actually added Dynos?

As for this other exception, let me take a look into that.  I am familiar with that error.

**Comment by scott** [comment]
I just looked at my Heroku logs- I am seeing the R14 error.  Currently demo.helpy.io is running on the Heroku free tier.  I researched it and the R14 error indicates your Heroku server is running out of physical memory and is swapping.  This can lead to performance issues.

I generally recommend at least 2GB of memory, and the free tier on Heroku only includes 1 dyno @512k of memory, but with a swap.  I found these articles that I thought were interesting- 

https://www.quora.com/How-powerful-is-one-Heroku-dyno
https://devcenter.heroku.com/articles/ruby-memory-use

**Comment by scott** [comment]
By the way, what version oh Helpy are you running?  I think that other error was fixed a while back.

**Comment by pepjo** [comment]
About the memory warning, I'm currently running on Hobby Dynos, I had done some research to and I had added a env variable: MALLOC_ARENA_MAX=2 as recommended somewhere in heroku docs. I have done this recently so I still don't know if it helps.

About the version, I usually merge your changes once a month or so, last time I did so was last friday. Since I do change somethings I usually get merge errors, maybe I resolved one badly. But It would be wired since I only modify css and html template files.

Tomorrow I'll try to merge again your changes and make a diff with your repo, I'll look for suspicious changes. But I don't feel that would be the problem... I'll keep you posted :smile:

**Comment by pepjo** [comment]
Ok, I did the diff and nothing was suspicious so I created a new free heroku dyno with a vanilla version of the helpy app.

The error persists. Although its a bit tricky since I cannot replicat it, only one member of the support team triggers it. And it's not only on one machine or connection, he has been able to replicate this on multiple computers and different networks.

This is a bit weird, but the logs don't lie...

**Comment by pepjo** [comment]
At last!! I have managed to get in an screen sharing session with the support member who was getting the error and now I know how to reproduce it:

1. You'll need to set up helpy with different languages
2. Create a new article
3. Go inside the article, change the language and write a title. Leave the body blank.
4. Save
5. You'll get an error :smile:

Now that we know exactly what's happening we can work around it :smile:

**Comment by scott** [comment]
Wow awesome work on recreating the issue!  I will see what is going on here...

**Comment by olliebennett** [comment]
The performance / memory usage aspect of this bug should be addressed at least in part by https://github.com/scott/helpy/pull/57.

**Comment by pepjo** [comment]
Great! thanks @olliebennett :smile:

**Comment by eddively** [comment]
How is performance on the free Heroku tier now?

**Comment by olliebennett** [comment]
Hey @pepjo - if the "quota exceeded" errors have not been showing in the latest code, do you think we could close this issue? Thanks!

**Comment by pepjo** [comment]
Sorry! yep, alright now :)

**Comment by Murithijoshua** [comment]
- this might be of help i managed to crack it.The reason is that due to the presence of many workers on the background check on the logs to solve this you need to run this command 
`heroku config:set WEB_CONCURRENCY=1`

-
