### ISSUE TITLE
Any Uploaded file results in 404. Logos in settings design as well as attachments in tickets

### ISSUE THREAD

**Issue by genachka** [helpyio/helpy#613]
Trying out Helpy. Using the docker image, updated it to latest release (1.2.1). Uploaded in `Settings` > `Design` header logo and favico. Shows that the path for them is: `/uploads/logos/logo.png` and `/uploads/logos/favicon.ico`

If I look within the docker image for the backend, there is physically a directory `/helpy/public/uploads/logos` which **does** contain the uploaded files. But from the web, I always get a 404 for them.

Also, any attachments I make in tickets results in 404 though I do see them physically uploaded.

I'm also not using Caddy for the frontend, but rather Nginx. All the default images, css, etc. works fine.

**Comment by scott** [comment]
Can you load the images in browser directly by URL?

**Comment by genachka** [comment]
No

**Comment by genachka** [comment]
Is this a known issue? Is there a workaround?

**Comment by scott** [comment]
Not that I am aware of it, that functionality works fine when directly installed.  I am guessing it could be a permissions issue- since the file is getting written but is not viewable even with the absolute URL.

**Comment by genachka** [comment]
The permissions were same as on assets folder. As a test to rule that out I gave uploads and everything under 777 and still not found. Sounds like a routes issue, but not sure where that gets configured or can check and what it should be set to to find public/uploads/logos/*

**Comment by genachka** [comment]
Also, I tried opening directly `/assets/logo.png` which worked but any file I tried copying in to there and opening results in 404 while I can open existing default files from there.

**Comment by genachka** [comment]
Noticed in  production.log the following error:
`F, [2017-04-27T01:50:48.415678 #206] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/uploads/logos/logo.png"):`

Is there a routes file I need to modify?

**Comment by lacion** [comment]
i am suffering this same exact issue running inside docker.

**Comment by freecrm** [comment]
I am having this issue too -- and I installed from Git, am running Webrick / built in web server.

This is a horrible buggy thing, are you guys just trying to make a buck on everyone's back, and not actually release what is running on your commercial offering?

It's rather suspicious....

**Comment by scott** [comment]
Hey Eric-   this was a specific issue with Docker, and has been fixed in #637  It was not clear if you are trying to use docker or just run it locally...  Can you describe more of what you have tried so we can see what is going wrong?

The commercial version does have some extra features and set up, but the open source works great for most people.

**Comment by freecrm** [comment]
As I stated, I ran the git clone, not docker.
Nothing works https://help.bcoiner.com
Everything 404
Even from Webrick http://help.bcoiner.com:3000/en

**Comment by freecrm** [comment]
Seems you can create a ticket, but hell if you can do any settings / changes on the app itself.

I sent you an invite, also I emailed you....I can send you the login for admin....it's like they've been saying here, broke as !@#*$!

**Comment by scott** [comment]
Can you run the test suite and post your results here: `bundle exec rake` and post results here.  I did a fresh install on my OSX localhost and everything works correctly, including all 1100+ tests pass. 

I suspect the issues you are having are related to Debian, which I have never installed to and can't help much on how to get Rails apps working.  That said, others have and maybe someone will see this and help out.  If I were you I create a new GH issue for "installing on debian" and see what happens.

**Comment by freecrm** [comment]
It's a mess.  I'll try again with the 1.2.1 release, the latest git clone has tons of issues.

**Comment by freecrm** [comment]
Well, that solves that -- I have 1.2.1 installed (latest release) and the bugs I was experiencing are gone!

I now have the older, staler bugs.

Yeah!

**Comment by scott** [comment]
@freecrm So I just did a fresh install to a brand new instance on Digital Ocean, Ubuntu 16.04 and followed all the instructions on http://support.helpy.io/en/knowledgebase/11-installing-helpy-yourself/docs/27-installing-helpy-on-ubuntu-14-04-using-passenger-and-nginx except I updated to ruby 2.3.3, Rails 4.2.8 and obviously ubuntu was a higher version and everything worked flawlessly.  File uploads, check.  Settings saved, check.  Full test suite green, check.  It possible you installed Rails 4.2.7 which is what was spec'd in the help doc and that was enough to blow it up.  Maybe try again with Rails 4.2.8?

**Comment by freecrm** [comment]
I'll give it a shot......Ruby woes ;-(

**Comment by freecrm** [comment]
**Fixed!**  Completely the Rails version, probably, but either way, great that it works.

Now on to better, undiscovered bugs.

**Comment by scott** [comment]
haha this time it was not a bug at all, but a bit of inaccuracy in the documentation.

**Comment by omata-metamax** [comment]
Hello,

This issue is still happening with the latest docker image.

**Comment by federico-d** [comment]
This issue is still happening with the latest docker image (release-2.8.0)

**Comment by sparrowme** [comment]
just cloned and brought up in docker - problem persists
container pulled ruby 2.5.9p229
